# toml netfliy: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  publish="dist/aot/"
  command="cp -R src/res/ext functions/json && npm run build-aot"
  functions="functions"
  environment={ BACKEND_URL=".netlify/functions/" }