# toml netfliy: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  publish="dist/aot/"
  command="cp deploy/util/* functions/nehubaConfig/ && cp -R src/res/ext functions/templates/json && cp -R src/res/ext functions/nehubaConfig/json && npm run build-aot && cd functions/datasets && npm i"
  functions="functions"
  environment={ BACKEND_URL=".netlify/functions/" }