# toml netfliy: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

[build]
  publish="dist/aot/"
  command="npm run build-aot"
  functions=".netlify/functions/"
  environment={
    BACKEND_URL="netlify_functions"
  }