name: e2e

on:
  pull_request:
    branches:
      - dev

env:
  DOCKER_IMAGE_NAME: interactive-viewer
  DOCKER_IMAGE_TAG: ${{ github.sha }}
  DOCKER_CONTAINER_NAME: gha-iav-built-${{ github.sha }}
  DOCKER_E2E_PPTR: gha-iav-e2e-pptr-${{ github.sha }}
  DOCKER_E2E_NETWORK: gha-dkr-network-${{ github.sha }}
  ATLAS_URL: http://gha-iav-built-${{ github.sha }}:3000/

jobs:
  buildimage:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build docker image ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
      run: |
        docker build --build-arg BACKEND_URL=${BACKEND_URL} -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
      env:
        BACKEND_URL: ${{ env.ATLAS_URL }}

  test:
    runs-on: self-hosted
    needs: buildimage
    steps:
    - name: run docker image ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} as container ${{ env.DOCKER_CONTAINER_NAME }}
      run: |
        docker run \
          --rm \
          --name ${DOCKER_CONTAINER_NAME} \
          --env HBP_CLIENTID=${{ secrets.HBP_CLIENTID }} \
          --env HBP_CLIENTSECRET=${{ secrets.HBP_CLIENTSECRET }} \
          --env REFRESH_TOKEN=${{ secrets.REFRESH_TOKEN }} \
          -dit \
          ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}

    - uses: actions/checkout@v1
    - name: Start pptr docker container with name ${{ env.DOCKER_E2E_PPTR }}
      run: |
        docker run --rm \
          --name ${DOCKER_E2E_PPTR} \
          -dt \
          puppeteer
        docker cp . ${DOCKER_E2E_PPTR}:/iav
        docker exec -u root ${DOCKER_E2E_PPTR} chown -R pptruser:pptruser /iav
        docker exec -t -w /iav ${DOCKER_E2E_PPTR} npm i
        docker exec -t -w /iav ${DOCKER_E2E_PPTR} npm run wd -- update --versions.chrome latest
        docker exec -t ${DOCKER_E2E_PPTR} npm i puppeteer
    - name: Setup docker network
      run: |
        docker network create ${{ env.DOCKER_E2E_NETWORK }}
        docker network connect ${{ env.DOCKER_E2E_NETWORK }} ${{ env.DOCKER_E2E_PPTR }}
        docker network connect ${{ env.DOCKER_E2E_NETWORK }} ${{ env.DOCKER_CONTAINER_NAME }}
    - name: run pptr tests - ${{ env.ATLAS_URL }}
      run: |
        docker exec --env ATLAS_URL=${ATLAS_URL} -t -w /iav ${DOCKER_E2E_PPTR} npm run e2e
    - name: cleanup, stop container ${{ env.DOCKER_CONTAINER_NAME }}
      if: success()
      run: |
        docker stop ${DOCKER_CONTAINER_NAME}
        docker stop ${DOCKER_E2E_PPTR}
        docker network rm ${DOCKER_E2E_NETWORK}
        docker rmi ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
