name: e2e

on:
  pull_request:
    branches:
      - dev

env:
  DOCKER_IMAGE_NAME: interactive-viewer
  DOCKER_IMAGE_TAG: ${{ github.sha }}
  DOCKER_SAVE_FILENAME: iav.tar.gz
  ARTEFACT_NAME: iav_docker_image
  DOCKER_CONTAINER_NAME: github-actions-iav-dkr-container

jobs:
  buildimage:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build docker image ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
      run: |
        docker build --build-arg BACKEND_URL=${BACKEND_URL} -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} .
      env:
        BACKEND_URL: http://localhost:3001

  test:
    runs-on: self-hosted
    needs: buildimage
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
        repository: 'FZJ-INM1-BDA/iv-automated-tests'
    - name: Install dependencies
      run: |
        npm i
    - name: run docker image ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
      run: |
        docker run -p 3001:3000 \
          --rm \
          --name ${DOCKER_CONTAINER_NAME} \
          --env HBP_CLIENTID=${{ env.HBP_CLIENTID }} \
          --env HBP_CLIENTSECRET=${{ env.HBP_CLIENTSECRET }} \
          -dit \
          ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    - name: sleep for 60s
      run: sleep 60s
    - name: run pptr tests - ${{ env.TEST_URL }}
      run: node ./node_modules/.bin/mocha ./test/databrowser.spec.js --timeout 1800000 
      env:
        TEST_URL: http://localhost:3001
    - name: cleanup, stop container ${{ env.DOCKER_CONTAINER_NAME }}
      if: always()
      run: docker stop ${DOCKER_CONTAINER_NAME}
    -name: cleanup, remove image ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
      if: success()
      run: docker rmi ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
