name: "[e2e] prod-specs"

on:
  workflow_dispatch:
    inputs:
      branch: 
        required: true
        default: dev
      url:
        required: true
        default: https://interactive-viewer-next.apps-dev.hbp.eu/

jobs:
  e2e:
    runs-on: [self-hosted, headless]
    strategy:
      matrix:
        protractor-spec: [
          './src/advanced/urlParsing.prod.e2e-spec.js',
          './src/advanced/pluginApi.prod.e2e-spec.js',
          './src/advanced/nonAtlasImages.prod.e2e-spec.js',
          './src/advanced/browsingForDatasets.prod.e2e-spec.js',
          './src/advanced/favDatasets.prod.e2e-spec.js',
          
          './src/selecting/region.prod.e2e-spec.js',
          './src/selecting/template.prod.e2e-spec.js',
          './src/selecting/atlas.prod.e2e-spec.js',

          './src/layout/home.prod.e2e-spec.js'
        ]
    env:
      PROTRACTOR_SPECS: ${{ matrix.protractor-spec }}
      ATLAS_URL: ${{ github.event.inputs.url }}
      PPTR_VERSION: "5.3.1"
      CHROMIUM_VERSION: "86.0.4240.0"

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Install dep
      run: |
        npm i
        npm run wd -- update --versions.chrome=${CHROMIUM_VERSION}
        npm i --no-save puppeteer@${PPTR_VERSION}
  
    - name: 'Run e2e for ${{ matrix.protractor-spec }} on ${{ github.event.inputs.url }}'
      run: npm run e2e
