name: '[undeploy from OKD]'

# only trigger on delete non master/staging branch
on: 
  delete:
    branches:
    - '!master'
    - '!staging'

jobs:
  remove-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2
    - name: 'Set env var'
      run: |
        echo "Using github.ref: $GITHUB_REF"
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
        echo "OKD_URL=https://okd-dev.hbp.eu:443" >> $GITHUB_ENV
        echo "OKD_SECRET=${{ secrets.OKD_DEV_SECRET }}" >> $GITHUB_ENV
        echo "OKD_PROJECT=interactive-atlas-viewer" >> $GITHUB_ENV
        echo "Remove deploy from dev cluster..."
    - name: 'Login via oc cli'
      run: |
        oc login $OKD_URL --token=$OKD_SECRET
        oc project $OKD_PROJECT
        # sanitized branchname == remove _ / and lowercase everything
        SANITIZED_BRANCH_NAME=$(echo ${BRANCH_NAME//[_\/]/} | awk '{ print tolower($0) }')
        echo "SANITIZED_BRANCH_NAME=$SANITIZED_BRANCH_NAME" >> $GITHUB_ENV
        echo "Working branch name: $BRANCH_NAME, sanitized branch name: $SANITIZED_BRANCH_NAME"
    - name: 'List and delete all labelled resoures'
      run: |
        oc get all \
          -l template=siibra-explorer-branch-deploy-template \
          -l app=siibra-explorer-branch-deploy-$SANITIZED_BRANCH_NAME
        oc delete all \
          -l template=siibra-explorer-branch-deploy-template \
          -l app=siibra-explorer-branch-deploy-$SANITIZED_BRANCH_NAME
